### ISSUE TITLE
Bug: Get signal SIGSEGV

### ISSUE THREAD

**Issue by mrbeardad** [juntaki/gogtags#13]
```
goroutine 1 [running]:
main.do.func1(0xc0000d4d40, 0x32, 0x0, 0x0, 0x696e80, 0xc00009ad20, 0x0, 0x0)
        /home/beardad/.local/go/pkg/mod/github.com/juntaki/gogtags@v0.0.0-20190923105759-784476838b04/main.go:49 +0x4c
path/filepath.walk(0xc0000aee10, 0x2e, 0x69a188, 0xc000110820, 0xc000105ee8, 0x0, 0x0)
        /usr/lib/go/src/path/filepath/path.go:434 +0x226
path/filepath.walk(0xc0000ae570, 0x26, 0x69a188, 0xc00009dba0, 0xc000105ee8, 0x0, 0x0)
        /usr/lib/go/src/path/filepath/path.go:438 +0x31b
path/filepath.walk(0xc0000ae060, 0x20, 0x69a188, 0xc00009d110, 0xc000105ee8, 0x0, 0x20)
        /usr/lib/go/src/path/filepath/path.go:438 +0x31b
path/filepath.Walk(0xc0000ae060, 0x20, 0xc00004eee8, 0xc00004ef00, 0x505255)
        /usr/lib/go/src/path/filepath/path.go:501 +0x113
main.do(0xc0000ae060, 0x20, 0xc0000ae060, 0x20)
        /home/beardad/.local/go/pkg/mod/github.com/juntaki/gogtags@v0.0.0-20190923105759-784476838b04/main.go:48 +0xeb
main.main()
        /home/beardad/.local/go/pkg/mod/github.com/juntaki/gogtags@v0.0.0-20190923105759-784476838b04/main.go:35 +0x1e5

```

**Comment by mrbeardad** [comment]
I have found the reason, there are some file that cannot have permission to open in the directory.
